#!/bin/sh

FILE3D="00000.3d"
FILEGEO="r000.geo"
ASE23DLOG="ase23d_output.log"
STRIPE3DLOG="stripe3d_output.log"

if [ ! -f "raw/$1.geo" ]
then
    echo "Incorrect file name. The base file name must match a .geo file that already exists in folder 'raw'."
    echo "Usage: ase2geo <file name without '-0*.ase'>"
    exit 1
fi

wine ase23d &> "$ASE23DLOG";

if [ ! -f "$FILE3D" ]
then
   echo "$FILE3D not found. Did you type the correct .ase & .hra files?"
   echo "Or you just forgot to press GO, bitch?"
else
    wine stripe3d &> "$STRIPE3DLOG";

    rm _tmp*
    rm tmp.obj*
    rm ftex
    rm fvrt
    rm $FILE3D

    if [ ! -f "$FILEGEO" ]
    then
       echo "Sorry, $FILEGEO was NOT generated successfully!"
    else
        mv -n "raw/$1.geo" "raw/$1.geo.bak"
        mv -f "$FILEGEO" "raw/$1.geo"

        echo "$1.geo generated and moved to RAW folder successfully."
        echo "If you are done converting the texture file then it's safe to compile."
    fi
fi
