cd raw
rem stages
call geo2obj r022.geo allinone
call geo2obj r173.geo allinone
call geo2obj r314.geo allinone
call geo2obj r382.geo allinone
call geo2obj r512.geo allinone
call geo2obj r615.geo allinone
call geo2obj r646.geo allinone
call geo2obj r711.geo allinone
call geo2obj r715.geo allinone
call geo2obj r784.geo allinone
call geo2obj r790.geo allinone
rem fighters
call geo2obj r003.geo allinone fighter
call geo2obj r004.geo allinone fighter
call geo2obj r005.geo allinone fighter
call geo2obj r006.geo allinone fighter
call geo2obj r007.geo allinone fighter
call geo2obj r008.geo allinone fighter
call geo2obj r009.geo allinone fighter
call geo2obj r010.geo allinone fighter
call geo2obj r011.geo allinone fighter
call geo2obj r012.geo allinone fighter
call geo2obj r013.geo allinone fighter
call geo2obj r014.geo allinone fighter
call geo2obj r015.geo allinone fighter
call geo2obj r016.geo allinone fighter
call geo2obj r017.geo allinone fighter
call geo2obj r019.geo allinone fighter
call geo2obj r020.geo allinone fighter
call geo2obj r713.geo allinone fighter
call geo2obj r714.geo allinone fighter
call geo2obj r725.geo allinone fighter
call geo2obj r727.geo allinone fighter
call geo2obj r728.geo allinone fighter
call geo2obj r730.geo allinone fighter
call geo2obj r731.geo allinone fighter
call geo2obj r733.geo allinone fighter
call geo2obj r734.geo allinone fighter
call geo2obj r736.geo allinone fighter
call geo2obj r737.geo allinone fighter
call geo2obj r739.geo allinone fighter
call geo2obj r741.geo allinone fighter
call geo2obj r742.geo allinone fighter
call geo2obj r744.geo allinone fighter
call geo2obj r745.geo allinone fighter
call geo2obj r747.geo allinone fighter
call geo2obj r748.geo allinone fighter
call geo2obj r750.geo allinone fighter
call geo2obj r752.geo allinone fighter
call geo2obj r754.geo allinone fighter
call geo2obj r755.geo allinone fighter
call geo2obj r759.geo allinone fighter
call geo2obj r761.geo allinone fighter
call geo2obj r762.geo allinone fighter
call geo2obj r764.geo allinone fighter
call geo2obj r765.geo allinone fighter
call geo2obj r787.geo allinone fighter
rem misc. objects
call geo2obj r510.geo allinone tubes big
call geo2obj r550.geo allinone
call geo2obj r720.geo allinone
call geo2obj r709.geo allinone misc big
call geo2obj r722.geo allinone blood
call geo2obj r723.geo allinone
call geo2obj r785.geo allinone select_screen
call geo2obj r786.geo allinone
call geo2obj r788.geo allinone text big
call geo2obj r792.geo allinone blood
call geo2obj r796.geo allinone hand_from_hell
call geo2obj r798.geo allinone dragon big
call geo2obj r018.geo
call geo2obj r021.geo
call geo2obj r023.geo
call geo2obj r090.geo
call geo2obj r511.geo
call geo2obj r579.geo
call geo2obj r710.geo
call geo2obj r712.geo
call geo2obj r716.geo
call geo2obj r718.geo
call geo2obj r719.geo
call geo2obj r721.geo
call geo2obj r724.geo
call geo2obj r726.geo
call geo2obj r729.geo
call geo2obj r732.geo
call geo2obj r735.geo
call geo2obj r738.geo
call geo2obj r740.geo
call geo2obj r743.geo
call geo2obj r746.geo
call geo2obj r749.geo
call geo2obj r751.geo
call geo2obj r753.geo
call geo2obj r756.geo
call geo2obj r757.geo
call geo2obj r758.geo
call geo2obj r760.geo
call geo2obj r763.geo
call geo2obj r766.geo
call geo2obj r767.geo
call geo2obj r768.geo
call geo2obj r769.geo
call geo2obj r770.geo
call geo2obj r771.geo
call geo2obj r772.geo
call geo2obj r773.geo
call geo2obj r774.geo
call geo2obj r775.geo
call geo2obj r776.geo
call geo2obj r777.geo
call geo2obj r778.geo
call geo2obj r779.geo
call geo2obj r780.geo
call geo2obj r781.geo
call geo2obj r782.geo
call geo2obj r783.geo
call geo2obj r789.geo
call geo2obj r793.geo
call geo2obj r794.geo
call geo2obj r795.geo
call geo2obj r797.geo
call geo2obj r799.geo
move r718*.rax ..\view\weapons
move r719*.rax ..\view\weapons
move *.rax ..\view
cd ..